name: Test spack build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get spack
        uses: actions/checkout@v2
        with:
          path: ./spack
          repository: spack/spack
          ref: develop

      - name: Setup E4S mirror
        run: |
          source spack/share/spack/setup-env.sh
          spack mirror add E4S https://cache.e4s.io
          spack buildcache keys -it

      - name: Build dolfinx
        run: |
          source spack/share/spack/setup-env.sh
          spack install py-fenics-dolfinx@master target=x86_64
